# Generated by Django 5.2.1 on 2025-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
